language: node_js

node_js: 
  - 7.9.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache: 
  directories: 
    - node_modules

branches: 
  only: 
    - origin

before_install:
  - npm install -g hexo
  - npm install -g hexo-cli

install: 
  - npm install -g
  # - npm install hexo-deployer-git --save
  # - npm install hexo-generator-archive --save
  # - npm install hexo-generator-category --save
  # - npm install hexo-generator-index --save
  # - npm install hexo-generator-searchdb --save
  # - npm install hexo-generator-tag --save
  # - npm install hexo-renderer-ejs --save
  # - npm install hexo-renderer-marked --save
  # - npm install hexo-renderer-stylus --save
  # - npm install hexo-server --save
  # - npm install hexo-wordcount --save

before_script: 
  - git config user.name "newpromise"
  - git config user.email "250621458@qq.com"
  - sed -i "s/gl_token/${GL_TOKEN}/g" ./_config.yml
  - hexo clean
 # - npm install -g gulp


script: 
  - hexo g
# after_script:
#   - sed -i "s/gl_token/${GL_TOKEN}/g" ./_config.yml
#   - hexo deploy
#   - cat ./public/2017/09/02/css居中效果/index.html
# E: Build LifeCycle

after_script: 
  - cd ./public
  - git init
  - git config user.name "newpromise"
  - git config user.email "250621458@qq.com"
  - git add .
  - git commit -m "update blog"
  - git pull --rebase
  - git push --set-upstream https://${GL_TOKEN}@github.com/newPromise/newPromise.github.io.git master

# env:
#  global:
#    - GH_REF: github.com/newPromise/newPromise.github.io.git