language: node_js
sudo: required

node_js: 
  - 7.9.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

branches:
  only:
    - origin

before_install:
  - npm install -g hexo
  - npm install -g hexo-cli

install:
  - npm install -g
  - npm install hexo-deployer-git --save
  - npm install hexo-generator-archive --save
  - npm install hexo-generator-category --save
  - npm install hexo-generator-index --save
  - npm install hexo-generator-searchdb --save
  - npm install hexo-generator-tag --save
  - npm install hexo-renderer-ejs --save
  - npm install hexo-renderer-marked --save
  - npm install hexo-renderer-stylus --save
  - npm install hexo-server --save
  - npm install hexo-wordcount --save

before_script:
 # - npm install -g gulp

script:
  - hexo generate

after_script:
  - git config user.name "newpromise"
  - git config user.email "250621458@qq.com"
  - sed -i "s/gl_token/${GL_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
  - cat ./public
# E: Build LifeCycle


# env:
#  global:
#    - GH_REF: github.com/newPromise/newPromise.github.io.git