language: node_js

node_js: 
  - v10.14.2
# 指定缓存模块，可选。缓存可加快编译速度。
cache: 
  directories: 
    - node_modules

branches: 
  only: 
    - origin

before_install:
  - npm install -g hexo-cli

install: 
  - npm install -g

before_script: 
  # - hexo clean
  - git config user.name "newpromise"
  - git config user.email "250621458@qq.com"
  - sed -i "s/gl_token/${GL_TOKEN}/g" ./_config.yml


script: 
  - hexo g

after_script:
  - git clone https://github.com/newPromise/newPromise.github.io .deploy_git
  - hexo deploy
