language: node_js
node_js: stable

before_install:
  - npm install -g hexo-cli

install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  # - cd ./public
  # - git init
  - git config user.name "newpromise"
  - git config user.email "250621458@qq.com"
  - git add .
  - git commit -m "update blog"
  - sed -i "s/gl_token/${GL_TOKEN}/g" ./_config.yml
  - hexo deploy
# E: Build LifeCycle

branches:
  only:
    - origin
# env:
#  global:
#    - GH_REF: github.com/newPromise/newPromise.github.io.git